lane :is_working_in_progress do |options|
  wip_text = options[:wip_text] ? options[:wip_text] : "WIP"

  pr_details = bitbucket_fetch(
    project_key: options[:project_key],
    repo_slug: options[:repo_slug],
    basic_creds: options[:basic_creds],
    request_id: options[:request_id]
  )

  pr_title = pr_details["rendered"]["title"]["raw"]

  pr_title.include? wip_text
end

lane :has_comment_message do |options|
  comments = bitbucket_list_comments(
    project_key: options[:project_key],
    repo_slug: options[:repo_slug],
    basic_creds: options[:basic_creds],
    request_id: options[:request_id]
  )

  comments_size = comments["size"]
  has_comment_already = false

  if comments_size > 0
    comments["values"].each do |comment|
      comment_text = comment["content"]["raw"]
      if comment_text == options[:message]
        has_comment_already = true
      end
    end
  end
  has_comment_already
end