lane :test do
  bitbucket_approve(
    base_url: "https://bitbucket-server-com",
    project_key: 'myproject',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: 1
  )

  bitbucket_decline(
    base_url: "https://bitbucket-server-com",
    project_key: 'myproject',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: 1
  )

  bitbucket_fetch(
    base_url: "https://bitbucket-server-com",
    project_key: 'myproject',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: 1
  )

  bitbucket_comment(
    base_url: "https://bitbucket-server-com",
    project_key: 'myproject',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: 1,
    message: "My comment message"
  )

  bitbucket_update_user_status(
    base_url: "https://bitbucket-server-com",
    project_key: 'myproject',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: 1,
    user_slug: "myuser" ,
    status: "NEEDS_WORK"
  )

  bitbucket_commit_status(
    base_url: "https://bitbucket-server-com",
    commit: "0000000000000000000000000000000000000000",
    commit_status_name: "This is test",
    commit_key: "test",
    commit_status: "SUCCESSFUL",
    basic_creds: "username:password",
    description: "description here",
    description_url: "http://your-build.com",
  )

  bitbucket_fetch_pull_requests(
    project_key: 'my-project',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    status: "OPENED",
    length: 10
  )

  bitbucket_request_changes(
    project_key: 'my-project',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: "1"
  )

  bitbucket_fetch_diffstat(
    project_key: 'my-project',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: "1",
    source_commit: "source-commit-hash",
    destination_commit: "destination-commit-hash"
  )

  bitbucket_list_comments_first_page(
    base_url: "https://bitbucket-server-com",
    project_key: 'myproject',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: 1
  )

  is_wip = bitbucket_fetch_is_pr_on_wip(
    base_url: "https://bitbucket-server-com",
    project_key: 'myproject',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: 1,
    wip_text: "[WIP]"
  )

  has_commented_already = bitbucket_pull_request_has_comment( 
    base_url: "https://bitbucket-server-com",
    project_key: 'myproject',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: 1,
    message: "My comment"
  )

  bitbucket_remove_request_changes(
    project_key: 'my-project',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: "1"
  )

  bitbucket_fetch_default_reviewers(
    project_key: 'my-project',
    repo_slug: 'my-repo',
    basic_creds: "username:password"
  )
  
  bitbucket_fetch_pull_request_by_id(
    project_key: 'my-project',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: "pr-id")

  bitbucket_get_development_branch(
    project_key: 'my-project',
    repo_slug: 'my-repo',
    basic_creds: "username:password"
  )

  bitbucket_fetch_pull_request_changed_files(
    project_key: 'my-project',
    repo_slug: 'my-repo',
    basic_creds: "username:password",
    request_id: "pr-id"
  )

  bitbucket_fetch_changed_lines_between_two_commits(
    project_key: 'my-project',
    repo_slug: 'my-repo',
    basic_creds: "username:password"
    source_commit: "abcd1234",
    destination_commit: "efgh5678",
    prefix: "+"
  )
end